### ISSUE TITLE
New URLs for map

### ISSUE THREAD

**Issue by achlong** [Hyperobjekt/el-map#20]
We want to move map 2.0 over to the current map URL, and create a new URL for map 1.0 so its still accessible for people who want to access it

**Comment by hoshmn** [comment]
@james-minton are you able to make this happen? 

all i know about the old map is that it's "deployed as a static site served over AWS S3 and CloudFront" as per the [readme](https://github.com/EvictionLab/eviction-maps#readme). seems like it's hosted [here](https://eviction-lab-map.s3.amazonaws.com/map/) -- that domain could continue to be used after pointing https://evictionlab.org/map to the new map (not sure about changing it). as for setting https://evictionlab.org/map to point to the new map, can that be configured in netlify?

**Comment by james-minton** [comment]
@hoshmn thanks for your help with this. Could use a bit more:

Updated `vite-config.js` in the production branch with `base: "/v2map/",` which produces a partially-loaded app at https://evictionlab.org/v2map/ . Making progress here. Still need to:

- [ ] figure out why Mapbox isn't loading (says API key is needed in console)
- [ ] determine why various assets aren't loading (icons, logos, etc.). Seeing 404s in console.
- [ ] bonus points: I have the `base` setting established just in `production`, which is fine for now. But might be better to apply this setting in all branches for continuity's sake, albeit with something specifying "only do this on the production branch." Don't know how to make that happen. (BTW I think this setting is just needed for the production environment because deploys to all other branches can safely go to Netlify, which doesn't need the base URL set.)

<img width="1270" alt="Screen Shot 2022-06-02 at 9 26 34 AM" src="https://user-images.githubusercontent.com/33635008/171642216-688e3518-e5c8-4d4a-b697-1f492e135399.png">

**Comment by hoshmn** [comment]
@james-minton major #progress! 🙌
1. TL;DR: I can fix this by moving the token into the repo. Are we already using a unique token for this project?
This is because the API token is an environment variable provided locally by my .env and is loaded into Netlify for the Netlify builds. Since the build in S3 is just a static file, I don't think there's any way to pass in variables. _Maybe_ there'd be a way to store it as a GitHub env var and pass it in during the GH action build process? But looking now that for other projects we just store it directly in the repo (MB tokens are exposed via every tile request anyways, so much different than say AWS keys).
2. Looks like those are imgs we directly set the /assets/... path for. I can add logic that conditionally prepends "/v2map" to the front of those paths (tinkering with them manually in devTools you'll see they do then show up).
3. Yeah, that would be ideal. Might use [this](https://vitejs.dev/config/#conditional-config)/use a modified build command (eg build-for-s3) in the [build action](https://github.com/Hyperobjekt/el-map/actions/runs/2428493797/workflow#L42) that runs `vite build` with a flag to set the base path (or maybe I'm over-complicating things?)
